### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by impero78** [agebrock/tunnel-ssh#46]
I have a couple of suggestions:
- avoid tunnel() altering (adding) the config properties (i have noticed that that in some cases). This might create regression issues for those who are relying on this undocumented functionality.
- instead, what about adding a config property/method to the Server object returned by tunnel(), so the original config params can be retrieved from the tunnel itself?

**Comment by agebrock** [comment]
Hi @impero78 

i completly agree with the first point. The config object should be immutable or at least not modified by the tunnel. 

The second point, returning the config object by the tunnel itself is a bigger topic, 
right now the config function itself is already excluded from the main code, since i want to implement different config generators. An example would be a ssh config parser to use the already configured aliases there. 
However i will keep your suggesting in mind in the next releases.
