### ISSUE TITLE
keepAlive does not seem to work

### ISSUE THREAD

**Issue by ceremcem** [agebrock/tunnel-ssh#69]
I'm setting `keepAlive: true` and connecting to the server. After a successful connection, I turn off my Wifi, so `tunnel` throws an error. Then I turn on the Wifi and expecting my code to reconnect, but nothing happens. The listening port created on localhost by `tunnel` is kept open though. 

Here is my code: 

```ls
require! 'tunnel-ssh': tunnel

config =
    username: \mysshuser
    host: \example.com
    port: 1234 
    privateKey:require('fs').readFileSync("#{process.env.HOME}/.ssh/id_rsa")
    keep-alive: yes
    dst-host: \localhost
    dst-port: 5589

t = tunnel config, (err, server) ->
    if err
        console.error "Something went wrong while opening tunnel: ", err
    else
        console.log "Tunnel succeeded"

t.on \error, (err) ->
    console.error "something went wrong"

# my application code goes here
```

Why doesn't `keepAlive` keeps the connection alive after a network failure?

**Comment by aberbegall** [comment]
Perhaps you can try to set 

`keepAlive:true`

instead of 

`keepAlive:yes`

**Comment by ceremcem** [comment]
`yes` and `on` are aliases for `true`.

**Comment by agebrock** [comment]
Hi there, the issue is not related to KeepAlive.
KeepAlive is just telling the tunnel to stay open even if there is no more active connection. 

What you need is some kind of reconnect, there is nothing implemented to do that automatically, the only thing you can do at the moment is listening to the Events and initialize the tunnel again. 

Let me know how you end up maybe we can do that in future.
